name: WORKFLOW - CI CD - Frontend & Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Test Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and run tests with coverage
        run: mvn clean verify

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/index.html

  backend-analysis:
    name: SonarCloud Backend Analysis
    runs-on: ubuntu-latest
    needs: backend-tests

    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Compile the project
        run: mvn clean verify

      - name: Run SonarCloud analysis
        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  docker-deploy-back:
    name: Build & Push Docker Images (Backend)
    runs-on: ubuntu-latest
    needs: 
      - backend-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back:$SHORT_SHA ./back
          docker tag ${{ secrets.DOCKER_USERNAME }}/bobapp-back:$SHORT_SHA ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

      - name: Push backend image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:$SHORT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

  frontend-tests:
    name: Test Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Upload Angular coverage report
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: front/coverage

  frontend-analysis:
    name: SonarCloud Frontend Analysis
    runs-on: ubuntu-latest
    needs: frontend-tests

    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarCloud analysis
        run: |
          npx sonar-scanner \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  docker-deploy-front:
    name: Build & Push Docker Images (Frontend)
    runs-on: ubuntu-latest
    needs: 
      - frontend-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-front:$SHORT_SHA ./front
          docker tag ${{ secrets.DOCKER_USERNAME }}/bobapp-front:$SHORT_SHA ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest

      - name: Push frontend image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:$SHORT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
